version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "org.springframework.security:*"
        schedule:
          interval: "daily"
      - dependency-name: "*"
        schedule:
          interval: "weekly"
    commit-message:
      prefix: "chore(deps):"
    reviewers:
      - "alana.correya@ust.com"
      - "keerthi.nallattesoman@ust.com"
    assignees:
      - "alana.correya@ust.com"
      - "keerthi.nallattesoman@ust.com"
    labels:
      - "security"
      - "version"
notifications:
  - email:
      recipients:
        - "alana.correya@ust.com"
        - "keerthi.nallattesoman@ust.com"
