version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      # For all dependencies
      - dependency-type: "all"
        schedule:
          interval: "daily"
          creates: "pull-request"
      # For security updates
      - dependency-type: "direct"
        security-updates: true
        schedule:
          interval: "daily"
          creates: "pull-request"
      # For version updates
      - dependency-type: "all"
        versioning-strategy: "widen"
        schedule:
          interval: "daily"
          creates: "pull-request"
    commit-message:
      prefix: "chore(deps):"
    reviewers:
      - "alana.correya@ust.com"
      - "keerthi.nallattesoman@ust.com"
    assignees:
      - "alana.correya@ust.com"
      - "keerthi.nallattesoman@ust.com"
    labels:
      - "dependencies"
      - "security"
