version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      # For dependencies from the "org.springframework.security" group
      - dependency-name: "org.springframework.security:*"
        schedule:
          interval: "daily"
          creates: "pull-request"
      # For all other dependencies
      - dependency-name: "*"
        schedule:
          interval: "daily"
          creates: "pull-request"
    commit-message:
      prefix: "chore(deps):"
    reviewers:
      - "alana.correya@ust.com"
      - "keerthi.nallattesoman@ust.com"
    assignees:
      - "alana.correya@ust.com"
      - "keerthi.nallattesoman@ust.com"
    labels:
      - "dependencies"
      - "security"
