version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "org.springframework.security:*"
        schedules:
          - interval: "daily"
            creates: "issues"
          - interval: "daily"
            creates: "pull-request"
            open-pull-requests-limit: 5
      - dependency-name: "*"
        schedules:
          - interval: "weekly"
            creates: "issues"
          - interval: "weekly"
            creates: "pull-request"
            open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps):"
    reviewers:
      - reviewers:
          - "alana.correya@ust.com"
          - "keerthi.nallattesoman@ust.com"
      - teams:
          - "alana.correya@ust.com"
    assignees:
      - "alana.correya@ust.com"
      - "keerthi.nallattesoman@ust.com"
    labels:
      - "security"
      - "version"
notifications:
  email:
    - "alana.correya@ust.com"
    - "keerthi.nallattesoman@ust.com"
